[package]
name = "ics2pda"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
dotenvy = "0.15.7"
tokio = { version = "1", features = ["full"] }
icalendar = "0.16.5"
chrono = "0.4.38"
toml = "0.8.19"
reqwest = "0.12.8"
